export const products=[
    {
     'name':'PineApple',
     'img':'https://www.bigbasket.com/media/uploads/p/xxl/10000156_21-fresho-pineapple.jpg',
     'quntity':'1',
     'unit':'Kg',
     'rating':'3.9',
     'ratings':'12',
     'price':'102',
     'dprice':'82',
     'discount':'20'   
    },
    {
        'name':'Orange',
        'img':'https://www.bigbasket.com/media/uploads/p/xxl/20000910_12-fresho-orange-imported.jpg',
        'quntity':'1',
        'unit':'Kg',
        'rating':'4.8',
        'ratings':'25',
        'price':'60',
        'dprice':'55',
        'discount':'8'   
       },
       {
        'name':'Banana',
        'img':'https://www.bigbasket.com/media/uploads/p/xxl/40229396_1-fresho-banana-nendran-organically-grown.jpg',
        'quntity':'1',
        'unit':'Kg',
        'rating':'4.0',
        'ratings':'30',
        'price':'90',
        'dprice':'72',
        'discount':'20'   
       },
       {
        'name':'Strawberry',
        'img':'https://www.bigbasket.com/media/uploads/p/xxl/10000263_12-fresho-strawberry.jpg',
        'quntity':'200',
        'unit':'gm',
        'rating':'3.9',
        'ratings':'12',
        'price':'68',
        'dprice':'68',
        'discount':null   
       },
       {
        'name':'Apple',
        'img':'https://www.bigbasket.com/media/uploads/p/xxl/40075384_12-fresho-apple-red-delicious-economy.jpg',
        'quntity':'1',
        'unit':'Kg',
        'rating':'3.8',
        'ratings':'19',
        'price':'120',
        'dprice':'120',
        'discount':null   
       },
       {
        'name':'Banganapalli Mango',
        'img':'https://www.bigbasket.com/media/uploads/p/l/10000298_10-fresho-banganapalli-mango.jpg',
        'quntity':'1',
        'unit':'Kg',
        'rating':'4.6',
        'ratings':'28',
        'price':'140',
        'dprice':'90',
        'discount':'38'   
       },
       {
        'name':'Kiwi',
        'img':'https://www.bigbasket.com/media/uploads/p/xxl/20000911_30-fresho-kiwi-green.jpg',
        'quntity':'3',
        'unit':'pcs',
        'rating':'3.9',
        'ratings':'12',
        'price':'99',
        'dprice':'99',
        'discount':null   
       },
       {
        'name':'Blueberry',
        'img':'https://www.bigbasket.com/media/uploads/p/xxl/30009286_7-fresho-blueberry.jpg',
        'quntity':'125',
        'unit':'g',
        'rating':'3.9',
        'ratings':'12',
        'price':'248',
        'dprice':'183',
        'discount':'26'   
       },
       {
        'name':'Watermelon',
        'img':'https://www.bigbasket.com/media/uploads/p/xxl/10000297_22-fresho-watermelon-striped-large.jpg',
        'quntity':'3-5',
        'unit':'Kg',
        'rating':'3.9',
        'ratings':'12',
        'price':'102',
        'dprice':'75',
        'discount':'20'   
       },
       {
        'name':'Raw Mango',
        'img':'https://www.bigbasket.com/media/uploads/p/xxl/10000588_12-fresho-raw-mango.jpg',
        'quntity':'1',
        'unit':'Kg',
        'rating':'3.9',
        'ratings':'12',
        'price':'80',
        'dprice':'64',
        'discount':'20'   
       },
]